### ISSUE TITLE
Use GitRef everywhere to resolve commit-ish

### ISSUE THREAD

**Issue by hifi** [git4p/git4p#12]
GitRef should naturally be loaded with `packed-refs` so that it can resolve names there but it should also do resolving from disk. There are a few calls (`Git->getTip` for example) that do their own resolving from disk directly and it fails badly when all refs are packed. The main Git class can initialize GitRef and use it for all resolving.

```
$git = new Git('/path/to/.git');
$master = $git->get('master'); // returns initialized GitCommit of master, guaranteed to return any GitObject or throw GitObjectNotFoundException
$parents = $master->parents(); // hashes like always, because a GitCommit doesn't know about the repo
$git->get($parents[0]) -> initialized GitCommit of parent[0]
```

In this example I renamed `getTip` into plain `get` as it's used to fetch any GitObject from the repository and it would use GitRef to always resolve the argument into hash that would be then fetched from the disk or from a pack.

I can do this refactor if allowed.

**Comment by hifi** [comment]
I think I melded two different things into one issue, sorry.

**Comment by mvdkleijn** [comment]
first off, thanks for the contribs.
second, I'm well aware the library is far from perfect, I'll work out the kinks. I started it for my amusement and I'd prefer to fix things myself. At least for now. :smile: Hope you understand.

**Comment by hifi** [comment]
Sure, I did my own thing from scratch in the end so I'll focus on that.
