### ISSUE TITLE
Commits are handled in a way it's possible to lose integrity

### ISSUE THREAD

**Issue by hifi** [git4p/git4p#4]
A commit that ends with NL is corrupted with `explode()` as the last NL is discarded.

For example your commit to this repository 25a26a427ca0f88f1248e0d0a50dd470ebd21ad8 has a message "Fix typo\n" and recalculating the SHA1 doesn't work because the tailing NL is discarded.

**Comment by mvdkleijn** [comment]
adding label for posterity
