### ISSUE TITLE
Namespaces and class naming

### ISSUE THREAD

**Issue by hifi** [git4p/git4p#9]
Could all classes be renamed so that they comply to PHP namespacing and it would make more sense for autoloader as well:

> GitObject.php -> Git\Object.php
> GitCommit.php -> Git\Commit.php

I know it adds a backslash to the full class name as well but it would keep the project more in-line with current standards.

I can do this refactor if given the go.

**Comment by mvdkleijn** [comment]
Though we can argue about the names I chose for the classes :wink: , the classes all comply to namespacing in general and PSR-4 specifically as far as I'm aware.

**Comment by hifi** [comment]
That was an oversight. Closing as invalid.
